---
apiVersion: v1
kind: Service
metadata:
  name: geonetwork
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: geonetwork
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonetwork
spec:
  selector:
    matchLabels:
      app: geonetwork
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geonetwork
    spec:
      containers:
      - name: geonetwork
        image: geonetwork:3.12.3-postgres
        resources:
          requests:
            memory: "8Gi"
            cpu: 4
        ports:
          - containerPort: 8080
        env:
          - name: DATA_DIR
            value: /var/lib/geonetwork/geonetwork_data
          - name: POSTGRES_DB_HOST
            value: "aurin-db.c5paqu2fyx9p.ap-southeast-2.rds.amazonaws.com"
          - name: POSTGRES_DB_PORT
            value: "5432"
          - name: POSTGRES_DB_NAME
            value: stratus
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
        volumeMounts:
        - mountPath: /var/lib/geonetwork
          name: geonetwork
      volumes:
      - name: geonetwork
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-geonetwork
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:816753656149:certificate/242af49d-9ed1-489a-9081-0b86624df3a9
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: geonetwork
              servicePort: 8080
