apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: infrastructure
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4.2
  nfs:
    server: "192.168.86.35"
    path: "/var/nfs/general"
  persistentVolumeReclaimPolicy: Retain
