apiVersion: v1
kind: Pod
metadata:
  name: postgis
  labels:
    name: postgis
spec:
  hostname: postgis
  containers:
  - name: postgis
    image: public.ecr.aws/b3b9b3w1/postgis
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASS
        value: postgres
      - name: POSTGRES_DBNAME
        value: stratus
      - name: ALLOW_IP_RANGE
        value: "<0.0.0.0/0>"
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgredb
  volumes:
    - name: postgredb
      persistentVolumeClaim:
        claimName: nfs

